/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodcount;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;  
  
/**
 *
 * @author serin
 */
public class updateIndividualCount extends javax.swing.JFrame {
String Email;
String messdutyEmail;
         JCheckBox checkBox1 = new JCheckBox("Breakfast",false);
        JCheckBox checkBox2 = new JCheckBox("Lunch", false);  
        JCheckBox checkBox3 = new JCheckBox("Snacks", false);  
        JCheckBox checkBox4 = new JCheckBox("Dinner", false);  
      
    /**
     * Creates new form viewIndividualCount
     */
    public updateIndividualCount() {
        initComponents();
    }

    updateIndividualCount(String email, String mdEmail) {
         initComponents();
         Email=email;
         messdutyEmail=mdEmail; 
          try
        {
     
            Mysqlconnect obj=new Mysqlconnect();
            ResultSet rs=obj.getResultset("Select * from count where email_id='"+email+"'");
            if(rs.next())
            { 
                if(rs.getInt("breakfast")==1)
                {
                    checkBox1.setSelected(true);
                    checkBox1.setBounds(100,5,50,50); 
                    checkBox1.setSize(100,100);
                    add(checkBox1);
                    checkBox1.setVisible(true);
                }
                if(rs.getInt("Lunch")==1)
                { 
                    checkBox2.setSelected(true);
                    checkBox2.setBounds(100,35, 50,50); 
                    checkBox2.setSize(100,100);
                    add(checkBox2);
                    
                    checkBox2.setVisible(true);
                }
                if(rs.getInt("Snacks")==1)
                {
                    checkBox3.setSelected(true);
                    checkBox3.setBounds(100,70, 50,50); 
                    checkBox3.setSize(100,100);
                   
                    add(checkBox3);
                    
                    checkBox3.setVisible(true);
                }
                if(rs.getInt("Dinner")==1)
                { 
                    checkBox4.setSelected(true);
                    checkBox4.setBounds(100,100, 50,50); 
                    checkBox4.setSize(100,100);
                   
                    add(checkBox4);
                    
                    checkBox4.setVisible(true);
                }
      
            }
           
            else
                            {JOptionPane.showMessageDialog(this, "Invalid Email");
                             }
                         
    }catch(Exception e){System.out.println(e);}}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int breakfast=0,lunch=0,snacks=0,dinner=0;
        if(checkBox1.isSelected())
            breakfast=1;
        else breakfast=0;
        if(checkBox2.isSelected())
            lunch=1;
        else lunch=0;
        
        if(checkBox3.isSelected())
           snacks=1;
        else snacks=0;
        
        if(checkBox4.isSelected())
         dinner=1;
        else dinner=0;
         try
        {
       
            
           
            System.out.println("yeaup");
            Class.forName("com.mysql.cj.jdbc.Driver");
         Connection conn =DriverManager.getConnection("jdbc:mysql://localhost:3306/foodcount","root","root");
         Mysqlconnect obj=new Mysqlconnect();
          String q="Update count set breakfast='"+breakfast+"',lunch='"+lunch+"',snacks='"+snacks+"',dinner='"+dinner+"' where email_id='"+Email+"'";
            PreparedStatement pmnt=conn.prepareStatement(q);           
            pmnt.executeUpdate();
            
        }
        catch(Exception e){  JOptionPane.showMessageDialog(this, "Cannot Update");
                   }        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new cutCount(messdutyEmail).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateIndividualCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateIndividualCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateIndividualCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateIndividualCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateIndividualCount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}

